name: Check format and build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: setup zig
        uses: goto-bus-stop/setup-zig@v2.1.1
      - name: Check format
        run: zig fmt --check src
      - name: Build
        run: zig build
        
